version: '3.0'

services:
  mysql8_skilla:
    container_name: mysql8_skilla
    image: mysql:8.0.33
    command: --default-authentication-plugin=mysql_native_password --collation-server=utf8_general_ci --character-set-server=utf8 --sql_mode="" --skip-log-bin
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_DATABASE: 'skilla'
    ports:
      - '3333:3306'
    networks:
      - skilla
  php8.3_skilla:
    container_name: php8.3_skilla
    platform: linux/x86_64
    build:
      context: ./
      dockerfile: ./docker/php8.3/Dockerfile
    stdin_open: true
    depends_on:
      - mysql8_skilla
    volumes:
      - ./:/var/skillaAPI
    networks:
      - skilla
  nginx_skilla:
    container_name: nginx_skilla
    image: nginx
    environment:
      - NGINX_PORT=80
    ports:
      - "89:80"
      - "8089:8080"
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/skillaAPI
      - ./docker/nginx/logs:/var/log/nginx/
    networks:
      - skilla
networks:
  skilla:
    driver: bridge
